on:
  schedule:
    - cron: "2 * * * *"
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version-file: ".nvmrc"
      - run: yarn install
      - name: Create .env and post
        run: |
          touch .env
          echo BLUESKY_USERNAME=$BLUESKY_USERNAME >> .env
          echo BLUESKY_PASSWORD=$BLUESKY_PASSWORD >> .env
          yarn run post
        env:
          BLUESKY_USERNAME: ${{ secrets.BLUESKY_USERNAME }}
          BLUESKY_PASSWORD: ${{ secrets.BLUESKY_PASSWORD }}